apiVersion: apps/v1
kind: Deployment  
metadata:
  name: proxy-app
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: proxy-app
  strategy: 
    type: RollingUpdate 
  template: 
    metadata: 
      labels:
        app: proxy-app 
    spec:
      containers:
      - name: proxy-app 
        image: aakashshinde09/project:proxy
        ports:
        - name: proxy
          containerPort: 80
          protocol: TCP 
